version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/react-app
    overwrite: true

  - source: scripts/
    destination: /var/www/react-app/scripts
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /var/www/react-app/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

