version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - curl -sL https://rpm.nodesource.com/setup_16.x | bash -
      - yum install -y nodejs
      - npm install
  pre_build:
    commands:
      - echo "Running tests"
      - npm run test 
  build:
    commands:
      - echo "Building the React application"
      - npm run build
  post_build:
    commands:  # Correct indentation here
      - echo "Starting Post-Build Phase"
      - echo "Zipping the built files"
      - zip -r build.zip build/
      - echo "Uploading artifact to S3"
      - aws s3 cp build.zip s3://buisness-optima-codebuild-artifact-storage/build.zip
      - echo "Notifying AWS CodeDeploy"
      - aws deploy create-deployment \
          --application-name MyReactApp \
          --deployment-group-name MyDeploymentGroup \
          --s3-location bucket=buisness-optima-codebuild-artifact-storage,bundleType=zip,key=build.zip

artifacts:
  files:
    - build/**/*
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*